import { YoutubeTranscript } from 'youtube-transcript';

export interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface AdChapter {
  title: string;
  startMs: number;
  endMs: number;
}

export interface VideoMetadata {
  title: string;
  author: string;
  subscriberCount: string;
  viewCount: string;
  publishDate: string;
}

interface TranscriptLine {
  text: string;
  start: number;
  dur: number;
}

export interface SubtitleResult {
  lines: TranscriptLine[];
  requestedLang: string;
  actualLang: string;
  availableLanguages: CaptionTrack[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
}

/**
 * Returns available caption languages for a video
 */
export async function getAvailableLanguages(videoID: string): Promise<CaptionTrack[]> {
  // youtube-transcript doesn't expose language list directly
  // Return English as default
  return [{
    languageCode: 'en',
    name: 'English',
    isAutoGenerated: true
  }];
}

/**
 * Fetches transcript using the youtube-transcript npm package
 */
export async function getSubtitles(options: {
  videoID: string;
  lang?: string;
  enableFallback?: boolean;
}): Promise<SubtitleResult> {
  const { videoID, lang = 'en', enableFallback = true } = options;

  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }

  // Build URL from video ID
  const url = `https://www.youtube.com/watch?v=${videoID}`;

  let transcript: Array<{ text: string; duration: number; offset: number; lang?: string }>;
  try {
    transcript = await YoutubeTranscript.fetchTranscript(url, { lang });
  } catch (err) {
    throw new Error(`Failed to fetch transcript: ${(err as Error).message}`);
  }

  // Convert to our format
  const lines: TranscriptLine[] = transcript.map(item => ({
    text: item.text,
    start: item.offset / 1000,  // Convert ms to seconds
    dur: item.duration / 1000
  }));

  const actualLang = transcript[0]?.lang || lang;

  return {
    lines,
    requestedLang: lang,
    actualLang,
    availableLanguages: [{
      languageCode: actualLang,
      name: actualLang,
      isAutoGenerated: true
    }],
    adChapters: [],
    metadata: {
      title: `YouTube Video ${videoID}`,
      author: 'Unknown',
      subscriberCount: '0',
      viewCount: '0',
      publishDate: 'Unknown'
    }
  };
}
